DELIMITER ;

#Users

CREATE USER 'ul_auth_user'@'%' IDENTIFIED BY 'oCBO1nbf0HUHFCTjbIFUsWf4Ki9ONavIOTISkyshy3JHjBabPcS4hh9pn8LTS4C';
CREATE USER 'ul_update_user'@'%' IDENTIFIED BY 'Knk8rzMNlZQxarrL46QMbCUjlkqVpCjHvpVtDyzQwAvahgARbcTi4SkWGe5uuEq';
CREATE USER 'ul_delete_user'@'%' IDENTIFIED BY 'uTm0N6wDi4P4e7uHxQcJecavUL0sxenFKx98gypKcfMLZ12yNf6SwBqfyQdjBhO';
CREATE USER 'ul_session_user'@'%' IDENTIFIED BY 'DjqzVtcUR6VHb4g9vXQcxX9Sdt6ldFw991aktrmJKv731VbCp3vU6uH30MR5owu';
CREATE USER 'ul_log_user'@'%' IDENTIFIED BY '8e2ucXaF4FyuiKuYKf0Wf4bQz6E56BFsQt3IMVMYvLHYEXrPHrHyylEsj4zXjFn';

CREATE USER 'cat_log_user'@'%' IDENTIFIED BY 'LitGL44YNOQEGJZSyt7jUvn0K8ywElkbke4MvzdhMX88ZrE4Qo65nDRDQfMx0kq';
CREATE USER 'cat_log_cln_user'@'%' IDENTIFIED BY '59zj8mRebRH0TtTqovJwo2EevUtAa52lir8UZC4Gm8OeVLsNzPRSnLPQZRfNSEY';
CREATE USER 'cat_read_user'@'%' IDENTIFIED BY 'BE4ZRxGBIStaGQTxIDsp53AOo15CC8MLjJ7jH04XZ8Xmx95Szpa0Bdo6k85KhM5';
CREATE USER 'cat_edit_user'@'%' IDENTIFIED BY 'ZDUGQSsDfj5TgPTW4YNc1ytewaMUTEnlaAf4BbMLI0NbzW2EDfObCwKWHE4P2uM';
CREATE USER 'cat_delete_user'@'%' IDENTIFIED BY 'TZERJqnuXas5O0gdfP6UENTSqj7w4XQTs2VhxVYh81fVjf94TR892mOSDmP4YWn';
CREATE USER 'cat_gp_mgt_user'@'%' IDENTIFIED BY 'p890a6bdeGNiBiy54n38SXmdzM7l1IMq82rPQ9YSJTFCg0cyuivTaDg9LAHJkIo';
CREATE USER 'cat_usr_mgt_user'@'%' IDENTIFIED BY 'DCoeK71fnjfqEt8DEYOUt8dglsBGfJRU7mlJcIN8trWzqlUkicg5tbIAQwm7Mt0';
CREATE USER 'cat_config_user'@'%' IDENTIFIED BY 'AdRfK71fnjfqEt8DTuiUt8dglsBGfJRU7mlJcIN8trWzql1s8cg5tbIAUJM09Ol';
CREATE USER 'cat_online_enrollment_user'@'%' IDENTIFIED BY 'AX4ZRgGBISjaGQTxIDsp53AOo15CC8MLjH7jH04XZ8Xmx68Szpa0Bdo6k85KhM5';

CREATE USER 'secureimage_user'@'%' IDENTIFIED BY 'RebRHqnuXas5O0gdjfqEtNTSqj7w4AOo15CC8MLjJ7jHjf94TRVjf94TR892mOS';


#Privileges

GRANT SELECT ON catequese.ul_logins TO 'ul_auth_user'@'%';
GRANT SELECT ON catequese.ul_blocked_ips TO 'ul_auth_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.ul_logins TO 'ul_update_user'@'%';
GRANT SELECT, DELETE ON catequese.ul_logins TO 'ul_delete_user'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON catequese.ul_sessions TO 'ul_session_user'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON catequese.ul_nonces TO 'ul_session_user'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON catequese.ul_blocked_ips TO 'ul_session_user'@'%';
GRANT SELECT, INSERT, DELETE ON catequese.ul_log TO 'ul_log_user'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON catequese.ul_blocked_ips TO 'ul_log_user'@'%';
GRANT SELECT, INSERT ON catequese.registosLog TO 'cat_log_user'@'%';
GRANT SELECT, UPDATE ON catequese.catequizando TO 'cat_log_user'@'%';
GRANT SELECT ON catequese.ul_log TO 'cat_log_user'@'%';
GRANT SELECT, DELETE ON catequese.registosLog TO 'cat_log_cln_user'@'%';
GRANT SELECT ON catequese.catequizando TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.escolaridade TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.pertence TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.grupo TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.inscreve TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.lecciona TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.catequista TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.familiar TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.casados TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.baptismo TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.primeiraComunhao TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.profissaoFe TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.confirmacao TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.registosLog TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.utilizador TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.cod_postais_paroquia TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.autorizacaoSaidaMenores TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.catequese_virtual TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.catequese_virtual_lock TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.pedidoRenovacaoMatricula TO 'cat_read_user'@'%';
GRANT SELECT ON catequese.pedidoInscricao TO 'cat_read_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.catequizando TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.escolaridade TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.pertence TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.grupo TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.inscreve TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.lecciona TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.catequista TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.familiar TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.casados TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.baptismo TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.primeiraComunhao TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.profissaoFe TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.confirmacao TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.utilizador TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.autorizacaoSaidaMenores TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.catequese_virtual TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.catequese_virtual_lock TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.pedidoRenovacaoMatricula TO 'cat_edit_user'@'%';
GRANT SELECT, UPDATE, INSERT ON catequese.pedidoInscricao TO 'cat_edit_user'@'%';
GRANT SELECT ON catequese.registosLog TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.escolaridade TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.inscreve TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.pertence TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.baptismo TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.profissaoFe TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.primeiraComunhao TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.confirmacao TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.casados TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.familiar TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.autorizacaoSaidaMenores TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.pedidoRenovacaoMatricula TO 'cat_edit_user'@'%';
GRANT DELETE ON catequese.pedidoInscricao TO 'cat_edit_user'@'%';
GRANT SELECT, DELETE ON catequese.catequizando TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.escolaridade TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.pertence TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.grupo TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.inscreve TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.familiar TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.casados TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.baptismo TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.primeiraComunhao TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.profissaoFe TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.confirmacao TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.autorizacaoSaidaMenores TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.catequese_virtual TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.catequese_virtual_lock TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.pedidoRenovacaoMatricula TO 'cat_delete_user'@'%';
GRANT SELECT, DELETE ON catequese.pedidoInscricao TO 'cat_delete_user'@'%';
GRANT SELECT, INSERT, DELETE ON catequese.pertence TO 'cat_gp_mgt_user'@'%';
GRANT SELECT, INSERT, DELETE ON catequese.grupo TO 'cat_gp_mgt_user'@'%';
GRANT SELECT, INSERT, DELETE ON catequese.lecciona TO 'cat_gp_mgt_user'@'%';
GRANT SELECT ON catequese.utilizador TO 'cat_gp_mgt_user'@'%';
GRANT SELECT ON catequese.catequista TO 'cat_gp_mgt_user'@'%';
GRANT SELECT, INSERT, UPDATE ON catequese.utilizador TO 'cat_usr_mgt_user'@'%';
GRANT SELECT, INSERT, UPDATE ON catequese.catequista TO 'cat_usr_mgt_user'@'%';
GRANT SELECT ON catequese.lecciona TO 'cat_usr_mgt_user'@'%';
GRANT SELECT ON catequese.ul_logins TO 'cat_usr_mgt_user'@'%';
GRANT SELECT, INSERT, UPDATE ON catequese.configuracoes TO 'cat_config_user'@'%';
GRANT INSERT ON catequese.pedidoRenovacaoMatricula TO 'cat_online_enrollment_user'@'%';
GRANT INSERT ON catequese.pedidoInscricao TO 'cat_online_enrollment_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON catequese.captcha_codes TO 'secureimage_user'@'%';